// lib/panel/techMaps.ts — statyczne mapy techniczne (EDU)
import { CANONICAL_LEVELS } from './techLevels';

export type TechMapItem = {
  id: string;
  asset: string;
	timeframe: 'M30' | 'H1' | 'H4' | 'D1' | 'W1' | 'MN';
  trend: string;                // opisowo (EDU)
  keyLevels: string[];          // kluczowe poziomy/strefy
  indicators: string[];         // wskaźniki/kontext techniczny
  volatility: string;           // opis zmienności (ATR/środowisko)
  scenarioNotes: string[];      // notatki scenariuszowe (EDU, warunkowe)
	updatedAt: string;
	// Opcjonalny horyzont ważności (UI filtruje po tym; domyślnie inferowane z timeframe)
	validFor?: '1d' | '1w' | '1m';
};

export const TECH_MAPS: TechMapItem[] = [
  {
    id: 'us100-h4',
    asset: 'US100',
    timeframe: 'H4',
    trend: 'Dominacja trendu wzrostowego, korekty płytkie. Wrażliwość na dane inflacyjne i komentarze z Fed.',
		keyLevels: ['25,300', '25,100', '24,650', '24,200'],
    indicators: ['MA(50/200) w układzie pro-wzrostowym', 'Momentum dodatnie na średnich TF'],
    volatility: 'ATR umiarkowany; skoki zmienności przy kluczowych odczytach (CPI/NFP).',
    scenarioNotes: [
			'Jeśli wybicie i akceptacja powyżej 25,300 → kontynuacja prawdopodobna przy potwierdzeniach szerokiego rynku.',
			'Jeśli powrót pod 25,100 i brak odkupienia → ryzyko głębszej korekty w strefę 24,650.',
    ],
    updatedAt: new Date().toISOString(),
  },
	{
		id: 'us100-m30',
		asset: 'US100',
		timeframe: 'M30',
		trend: 'Trend intraday wzrostowy/kanał; szybkie korekty podczas publikacji danych.',
		keyLevels: ['25,150', '25,080', '25,020', '24,960'],
		indicators: ['MA(20/50) jako prowadzące', 'RSI: krótkie przegrzania po wybiciach'],
		volatility: 'ATR wyższy w godzinach USA oraz przy publikacjach; sprzyja scalpowi na retestach.',
		scenarioNotes: [
			'Akceptacja nad 25,150 przy rosnącym breadth → kontynuacja do 25,300.',
			'Powrót pod 25,080 bez odkupienia → test 25,020/24,960.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'us100-h1',
		asset: 'US100',
		timeframe: 'H1',
		trend: 'Wzrosty z płytkimi korektami; rotacja sektorowa nadaje tempo.',
		keyLevels: ['25,300', '25,100', '24,800', '24,650'],
		indicators: ['MA(50) jako wsparcie', 'MACD dodatni na H1'],
		volatility: 'ATR umiarkowany; skoki przy CPI/PCE i konferencjach Fed.',
		scenarioNotes: [
			'Utrzymanie nad 25,100 → szansa na 25,300.',
			'Zamknięcie pod 24,800 → ryzyko zejścia do 24,650.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'us100-d1',
		asset: 'US100',
		timeframe: 'D1',
		trend: 'Dominujący trend wzrostowy, sentyment pozytywny; ryzyko przegrzania w krótkim terminie.',
		keyLevels: ['25,500', '25,300', '24,650', '24,200'],
		indicators: ['MA(50/200) byczy układ', 'RSI: przegrzanie po parabolicznych ruchach'],
		volatility: 'ATR stabilny; zmienność rośnie wokół danych inflacyjnych i wyników big tech.',
		scenarioNotes: [
			'Akceptacja nad 25,300 → otwiera drogę do 25,500.',
			'Powrót pod 24,650 → ryzyko zejścia do 24,200.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'us100-w1',
		asset: 'US100',
		timeframe: 'W1',
		trend: 'Trend tygodniowy wzrostowy; korekty zwykle zatrzymują się na MA(20/50).',
		keyLevels: ['25,800', '25,300', '24,200', '23,400'],
		indicators: ['MA(20/50) trzyma strukturę', 'MACD dodatni na W1'],
		volatility: 'ATR tygodniowy umiarkowany; zwiększa się przy zmianie polityki monetarnej.',
		scenarioNotes: [
			'Świece tygodniowe z zamknięciem nad 25,300 → kontynuacja trendu.',
			'Zamknięcie tygodnia pod 24,200 → ostrzeżenie przed głębszą korektą do 23,400.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'us100-mn',
		asset: 'US100',
		timeframe: 'MN',
		trend: 'Wieloletni trend wzrostowy napędzany zyskami sektora technologicznego.',
		keyLevels: ['26,300', '25,300', '23,500', '22,300'],
		indicators: ['MA(50m) rosnąca', 'RSI miesięczny: obserwuj dywergencje'],
		volatility: 'Zmienność miesięczna rośnie po cyklicznych pivotach Fed.',
		scenarioNotes: [
			'Zamknięcia miesięczne nad 25,300 utrzymują strukturę pro-wzrostową.',
			'Miesięczne powroty pod 23,500 to ryzyko wejścia w dłuższą konsolidację.',
		],
		updatedAt: new Date().toISOString(),
	},
  {
    id: 'xauusd-h1',
    asset: 'XAUUSD',
    timeframe: 'H1',
    trend: 'Wzrosty zależne od kondycji USD i rentowności; krótkie, dynamiczne fale po publikacjach.',
		keyLevels: ['4,300', '4,285', '4,268', '4,250'],
    indicators: ['RSI: przegrzanie bywa krótkie', 'MA(50) jako dynamiczne wsparcie/opor'],
    volatility: 'ATR podwyższony w okolicach publikacji danych inflacyjnych i NFP.',
    scenarioNotes: [
			'Akceptacja powyżej 4,285 przy słabnącym USD wspiera trend wyżej, dopóki 4,268 broni się w retestach.',
			'Przełamanie 4,268 przy silnym USD może prowadzić do testu 4,250 — scenariusz warunkowy.',
    ],
    updatedAt: new Date().toISOString(),
  },
	{
		id: 'xauusd-m30',
		asset: 'XAUUSD',
		timeframe: 'M30',
		trend: 'Ruchy impulsowe; częste wybicia i szybkie retesty w pobliżu danych.',
		keyLevels: ['4,292', '4,285', '4,276', '4,268'],
		indicators: ['MA(20/50) nawigacja intraday', 'RSI szybkie strefy przegrzania'],
		volatility: 'ATR wysoki; ryzyko fałszywych pierwszych reakcji.',
		scenarioNotes: [
			'Retest 4,285 od góry i słaby DXY → ruch do 4,292.',
			'Złamanie 4,268 przy silnym USD → 4,260/4,250.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'xauusd-h4',
		asset: 'XAUUSD',
		timeframe: 'H4',
		trend: 'Kanał wzrostowy; cofnięcia zwykle trzymane przez MA(50).',
		keyLevels: ['4,315', '4,300', '4,285', '4,268'],
		indicators: ['MA(50) wsparcie dynamiczne', 'RSI: szukaj dywergencji na szczytach'],
		volatility: 'ATR średni; narasta przy CPI/PCE i NFP.',
		scenarioNotes: [
			'Akceptacja nad 4,300 → cel 4,315.',
			'Powrót pod 4,285 → test 4,268.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'xauusd-d1',
		asset: 'XAUUSD',
		timeframe: 'D1',
		trend: 'Wzrosty podtrzymywane spadkiem realnych rentowności; korekty dynamiczne.',
		keyLevels: ['4,350', '4,320', '4,285', '4,250'],
		indicators: ['MA(50/200) rosnące', 'Korelacja odwrotna z DXY'],
		volatility: 'ATR wyższy w okresach publikacji inflacyjnych i decyzji FOMC.',
		scenarioNotes: [
			'Zamknięcia nad 4,320 → utrzymanie momentum do 4,350.',
			'Domknięcia pod 4,285 → ryzyko zejścia do 4,250.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'xauusd-w1',
		asset: 'XAUUSD',
		timeframe: 'W1',
		trend: 'Struktura tygodniowa pro-wzrostowa; złoto zyskuje przy risk-off i spadku real yields.',
		keyLevels: ['4,380', '4,320', '4,250', '4,180'],
		indicators: ['MA(20/50) w trendzie', 'MACD dodatni na W1'],
		volatility: 'ATR tygodniowy umiarkowany do wysokiego przy zwrotach polityki monetarnej.',
		scenarioNotes: [
			'Świeca tygodniowa nad 4,320 → kontynuacja w kierunku 4,380.',
			'Zamknięcie tygodnia pod 4,250 → ostrzeżenie o głębszej korekcie.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'xauusd-mn',
		asset: 'XAUUSD',
		timeframe: 'MN',
		trend: 'Trend wieloletni wzrostowy wspierany popytem banków centralnych i polityką monetarną.',
		keyLevels: ['4,400', '4,320', '4,200', '4,050'],
		indicators: ['MA(50m) wzrostowa', 'RSI: obserwuj długoterminowe dywergencje'],
		volatility: 'Zmienność miesięczna rośnie podczas cykli inflacyjnych i zmian stóp.',
		scenarioNotes: [
			'Miesięczne wybicia nad 4,320 utrzymują trend do 4,400.',
			'Powrót poniżej 4,200 sygnalizuje szeroką konsolidację.',
		],
		updatedAt: new Date().toISOString(),
	},
  {
    id: 'eurusd-d1',
    asset: 'EURUSD',
    timeframe: 'D1',
    trend: 'Boczny z lekkim biasem w górę; zależny od różnicy stóp i perspektyw inflacyjnych EZ/USA.',
    keyLevels: ['1.1200', '1.1050', '1.0950', '1.0850'],
    indicators: ['MA(200) blisko ceny jako filtr kierunkowy', 'Momentum neutralne, wrażliwe na dane'],
    volatility: 'ATR umiarkowany; większy ruch przy CPI/NFP oraz konferencjach banków centralnych.',
    scenarioNotes: [
      'Utrzymanie powyżej 1.1050 przy gołębim USD wspiera test 1.1200, o ile dane z EZ nie rozczarują.',
      'Powrót pod 1.0950 przy jastrzębim Fed zwiększa ryzyko zejścia w kierunku 1.0850.',
    ],
    updatedAt: new Date().toISOString(),
  },
	{
		id: 'eurusd-m30',
		asset: 'EURUSD',
		timeframe: 'M30',
		trend: 'Range intraday ze skłonnością do fałszywych wybić w czasie publikacji danych.',
		keyLevels: ['1.1050', '1.1015', '1.0990', '1.0950'],
		indicators: ['MA(20/50) waha się wokół ceny', 'RSI: szybkie powroty do 50'],
		volatility: 'ATR niski do umiarkowanego poza godzinami danych.',
		scenarioNotes: [
			'Retest 1.1015 od góry → ruch do 1.1050.',
			'Złamanie 1.0990 → test 1.0950.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'eurusd-h1',
		asset: 'EURUSD',
		timeframe: 'H1',
		trend: 'Boczny z lekkim pro-euro biasem; wrażliwy na różnicę stóp i DXY.',
		keyLevels: ['1.1070', '1.1050', '1.1000', '1.0950'],
		indicators: ['MA(50) jako filtr kierunku', 'RSI: testy strefy 40–60'],
		volatility: 'ATR umiarkowany; wzrost przy CPI/PMI i payrolls.',
		scenarioNotes: [
			'Akceptacja nad 1.1050 → 1.1070.',
			'Powrót pod 1.1000 → 1.0950.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'eurusd-h4',
		asset: 'EURUSD',
		timeframe: 'H4',
		trend: 'Szeroka konsolidacja; kierunek zależny od relacji EBC–Fed.',
		keyLevels: ['1.1100', '1.1050', '1.0950', '1.0880'],
		indicators: ['MA(200) blisko ceny', 'MACD słaby'],
		volatility: 'ATR umiarkowany; wzrost przy posiedzeniach banków centralnych.',
		scenarioNotes: [
			'Zamknięcie nad 1.1050 → test 1.1100.',
			'Zamknięcie pod 1.0950 → 1.0880.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'eurusd-w1',
		asset: 'EURUSD',
		timeframe: 'W1',
		trend: 'Neutralny do lekko wzrostowego; główny czynnik: różnica realnych stóp.',
		keyLevels: ['1.1200', '1.1050', '1.0850', '1.0700'],
		indicators: ['MA(20/50) płaskie', 'RSI blisko 50'],
		volatility: 'ATR tygodniowy umiarkowany.',
		scenarioNotes: [
			'Tygodniowe zamknięcie nad 1.1050 → 1.1200.',
			'Tygodniowe zamknięcie pod 1.0850 → 1.0700.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'eurusd-mn',
		asset: 'EURUSD',
		timeframe: 'MN',
		trend: 'Długoterminowa konsolidacja z szerokimi wahaniami cyklicznymi.',
		keyLevels: ['1.1500', '1.1200', '1.0500', '1.0000'],
		indicators: ['MA(50m) płaska', 'RSI miesięczny neutralny'],
		volatility: 'Zmienność miesięczna zależna od cykli stóp i inflacji.',
		scenarioNotes: [
			'Miesięczne zamknięcie nad 1.1200 → kierunek 1.1500.',
			'Powrót pod 1.0500 → ryzyko testu parytetu.',
		],
		updatedAt: new Date().toISOString(),
	},

	// Indeksy
	{
		id: 'us500-h4',
		asset: 'US500',
		timeframe: 'H4',
		trend: 'Struktura wzrostowa utrzymana; rotacja sektorowa nadaje rytm fali. Reakcje na dane makro przewyższają technikę w krótkim terminie.',
		keyLevels: ['5,000', '4,955', '4,900', '4,860', '4,800'],
		indicators: ['MA(50) powyżej MA(200) — układ byczy', 'MACD dodatni na H4/D1', 'Breadth umiarkowany; wrażliwy na dane inflacyjne'],
		volatility: 'ATR umiarkowany; podwyższa się przy CPI/PCE i posiedzeniach Fed.',
		scenarioNotes: [
			'Akceptacja powyżej 5,000 i retesty trzymane → kontynuacja z targetami przy 5,050–5,080.',
			'Domknięcie poniżej 4,900 bez szybkiego odkupienia → ryzyko pogłębienia korekty do 4,860/4,800.',
			'Wzrost VIX powyżej 18–20 często zapowiada szarpaną zmienność i fałszywe wybicia.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'de40-h4',
		asset: 'DE40',
		timeframe: 'H4',
		trend: 'Trend wzrostowy z okresowymi konsolidacjami; zależność od koniunktury EZ i EUR.',
		keyLevels: ['17,100', '16,900', '16,700', '16,500'],
		indicators: ['MA(50) jako wsparcie dynamiczne', 'RSI blisko 50 podczas konsolidacji', 'Korelacja z EUR i rentownościami DE'],
		volatility: 'ATR umiarkowany, zwiększa się podczas publikacji ZEW, PMI i CPI dla EZ/DE.',
		scenarioNotes: [
			'Utrzymanie nad 16,900 → szansa na powrót do 17,100, jeśli EUR nie umacnia się zbyt gwałtownie.',
			'Zamknięcie pod 16,700 i brak popytu → ryzyko zejścia do 16,500.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'de40-m30',
		asset: 'DE40',
		timeframe: 'M30',
		trend: 'Intraday: naprzemiennie krótkie fale trendowe i konsolidacje; wrażliwy na EKB i dane EZ.',
		keyLevels: ['17,020', '16,960', '16,900', '16,820'],
		indicators: ['MA(20/50) prowadzące na M30', 'RSI szybkie powroty do strefy 50'],
		volatility: 'ATR rośnie podczas sesji EU i przy publikacjach PMI/IFO/ZEW.',
		scenarioNotes: [
			'Retest 16,960 od góry → szansa na 17,020.',
			'Złamanie 16,900 → 16,820 w razie risk-off.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'de40-h1',
		asset: 'DE40',
		timeframe: 'H1',
		trend: 'Wzrosty przerywane konsolidacjami; zależność od EURUSD i spreadów DE/US.',
		keyLevels: ['17,080', '16,980', '16,900', '16,780'],
		indicators: ['MA(50) wsparcie trendowe', 'RSI: dywergencje na wierzchołkach fal'],
		volatility: 'ATR umiarkowany; skoki przy CPI EZ i wypowiedziach EBC.',
		scenarioNotes: [
			'Akceptacja nad 16,980 → ruch do 17,080.',
			'Powrót pod 16,900 → test 16,780.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'de40-d1',
		asset: 'DE40',
		timeframe: 'D1',
		trend: 'Średnioterminowy trend wzrostowy; korekty kontrolowane strefami popytu.',
		keyLevels: ['17,300', '17,100', '16,700', '16,300'],
		indicators: ['MA(50/200) w lekkim układzie byczym', 'MACD dodatni na D1'],
		volatility: 'ATR dzienny umiarkowany; rośnie przy zwrotach na EUR i rentownościach.',
		scenarioNotes: [
			'Domknięcia nad 17,100 → otwierają przestrzeń do 17,300.',
			'Domknięcia pod 16,700 → sygnał ryzyka zejścia do 16,300.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'de40-w1',
		asset: 'DE40',
		timeframe: 'W1',
		trend: 'Trend tygodniowy lekko wzrostowy; ekspozycja na cykl EZ i eksport.',
		keyLevels: ['17,500', '17,100', '16,300', '15,800'],
		indicators: ['MA(20/50) jako filtry trendu', 'MACD dodatni na W1'],
		volatility: 'ATR tygodniowy umiarkowany; zwiększa się przy zmianach forward guidance EBC.',
		scenarioNotes: [
			'Zamknięcie tygodnia nad 17,100 → kontynuacja w kierunku 17,500.',
			'Zamknięcie tygodnia pod 16,300 → ostrzeżenie o pogłębieniu korekty.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'de40-mn',
		asset: 'DE40',
		timeframe: 'MN',
		trend: 'Długoterminowo lekki trend wzrostowy; wpływ mają cykle przemysłowe EZ.',
		keyLevels: ['18,000', '17,100', '15,800', '14,800'],
		indicators: ['MA(50m) płaska do lekko rosnącej', 'RSI miesięczny blisko 50'],
		volatility: 'Zmienność miesięczna umiarkowana, rośnie przy zmianach polityki EBC.',
		scenarioNotes: [
			'Miesięczne zamknięcie nad 17,100 → wzmacnia scenariusz do 18,000.',
			'Powrót pod 15,800 → ryzyko wejścia w dłuższą konsolidację.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'us30-h4',
		asset: 'US30',
		timeframe: 'H4',
		trend: 'Szeroka konsolidacja z lekkim biasem w górę; wrażliwy na wahania rentowności i USD.',
		keyLevels: ['39,000', '38,600', '38,100', '37,600'],
		indicators: ['MA(200) jako filtr trendu', 'RSI z częstymi dywergencjami na lokalnych szczytach', 'Oscylator stochastyczny pomocny w range'],
		volatility: 'ATR niewielki do umiarkowanego; skoki przy NFP i CPI.',
		scenarioNotes: [
			'Akceptacja nad 39,000 wspierana breadth → kontynuacja do 39,400.',
			'Odwrócenie pod 38,600 z szeroką podażą → test 38,100.',
		],
		updatedAt: new Date().toISOString(),
	},

	// Towary
	{
		id: 'xagusd-h1',
		asset: 'XAGUSD',
		timeframe: 'H1',
		trend: 'Ruchy skokowe, zwykle bardziej zmienne niż złoto; ścisły związek z USD i sentymentem risk-on/off.',
		keyLevels: ['29.50', '28.90', '28.40', '27.80'],
		indicators: ['MA(50) jako prowadząca ścieżka', 'RSI szybkie przegrzania — krótkie „blow-offy”', 'Korelacja z XAUUSD i DXY'],
		volatility: 'ATR podwyższony przez mikrostrukturalne wybicia; publikacje CPI/NFP wzmagają ruchy.',
		scenarioNotes: [
			'Akceptacja powyżej 28.90 przy słabnącym DXY → szansa na 29.50.',
			'Powrót pod 28.40 i brak odkupienia → ryzyko zejścia w 27.80.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'wti-h4',
		asset: 'WTI',
		timeframe: 'H4',
		trend: 'Trend boczno-wzrostowy zależny od newsflow podażowo-popytowego i ryzyk geopolitycznych.',
		keyLevels: CANONICAL_LEVELS.WTI,
		indicators: ['MA(50) prowadzi swing', 'Backwardation/contango jako filtr kontekstu', 'RSI dywergencje na zwrotach'],
		volatility: 'ATR umiarkowany do wysokiego; silnie reaguje na raporty EIA, OPEC oraz geopolitykę.',
		scenarioNotes: [
			'Utrzymanie powyżej 76 → otwiera drogę do 78, jeśli zapasy maleją.',
			'Zamknięcie pod 74 przy rosnących zapasach → test 72/70.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'brent-h4',
		asset: 'BRENT',
		timeframe: 'H4',
		trend: 'Lekko wzrostowy kanał; wrażliwy na decyzje OPEC+ i nastroje globalne.',
		keyLevels: CANONICAL_LEVELS.BRENT,
		indicators: ['MA(50) wsparcie w trendzie', 'RSI: strefa 40–60 w konsolidacji', 'Spread Brent-WTI jako filtr relatywny'],
		volatility: 'ATR umiarkowany; nagłe skoki przy ryzykach geopolitycznych i awariach infrastruktury.',
		scenarioNotes: [
			'Akceptacja nad 81 → potencjał do 83, jeśli WTI również rośnie.',
			'Przełamanie 79 → otwiera drogę do 77 w razie risk-off.',
		],
		updatedAt: new Date().toISOString(),
	},

	// FX
	{
		id: 'gbpusd-d1',
		asset: 'GBPUSD',
		timeframe: 'D1',
		trend: 'Konsolidacja w szerokim zakresie; balans między polityką BoE a Fed.',
		keyLevels: ['1.2850', '1.2700', '1.2550', '1.2400'],
		indicators: ['MA(200) jako filtr dominującego kierunku', 'RSI neutralny z częstymi dywergencjami', 'ATR umiarkowany — sprzyja swingom'],
		volatility: 'ATR umiarkowany; wzmożenie przy CPI UK, payrolls USA i decyzjach BoE/Fed.',
		scenarioNotes: [
			'Obrona 1.2700 i słabszy USD → retest 1.2850.',
			'Zamknięcie pod 1.2550 przy jastrzębim Fed → ryzyko 1.2400.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'usdjpy-d1',
		asset: 'USDJPY',
		timeframe: 'D1',
		trend: 'Silna zależność od różnic rentowności; struktura wzrostowa z ryzykiem gwałtownych korekt po interwencjach.',
		keyLevels: ['160.0', '158.0', '156.5', '155.0'],
		indicators: ['MA(50) powyżej MA(200)', 'RSI często przegrzany podczas silnych impulsów', 'Monitoruj wypowiedzi BoJ/MoF'],
		volatility: 'ATR podwyższony; ryzyko skoków przy interwencjach i niespodziankach CPI USA/JPN.',
		scenarioNotes: [
			'Akceptacja nad 158.0 → kierunek 160.0, dopóki nie pojawi się sygnał interwencyjny.',
			'Powrót pod 156.5 i brak odkupienia → test 155.0.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'eurpln-d1',
		asset: 'EURPLN',
		timeframe: 'D1',
		trend: 'Średnioterminowy range sterowany różnicą stóp i napływem kapitału do EM.',
		keyLevels: ['4.40', '4.35', '4.30', '4.25'],
		indicators: ['MA(200) jako filtr', 'RSI neutralny', 'Korelacja z koszykiem CEE i DXY'],
		volatility: 'ATR niewielki do umiarkowanego; skacze przy posiedzeniach RPP i EBC.',
		scenarioNotes: [
			'Obrona 4.35 → szansa na powrót do 4.40 przy risk-off.',
			'Złamanie 4.30 → kierunek 4.25 przy risk-on i mocnym PLN.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'usdpln-d1',
		asset: 'USDPLN',
		timeframe: 'D1',
		trend: 'Kierunek wyznacza globalny USD; lokalnie wrażliwy na politykę RPP i przepływy EM.',
		keyLevels: ['4.10', '4.00', '3.95', '3.90'],
		indicators: ['MA(50/200) — filtr trendu', 'RSI: strefa 40–60 w konsolidacjach', 'Korelacja odwrotna z EURUSD/DXY'],
		volatility: 'ATR umiarkowany; skoki przy CPI USA, NFP oraz konferencjach RPP.',
		scenarioNotes: [
			'Obrona 4.00 i wzrost DXY → ruch do 4.10.',
			'Zamknięcie pod 3.95 przy risk-on → test 3.90.',
		],
		updatedAt: new Date().toISOString(),
	},

	// Akcje (D1 — kontekst edukacyjny)
	{
		id: 'aapl-d1',
		asset: 'AAPL',
		timeframe: 'D1',
		trend: 'Dominacja trendu wzrostowego; korekty po wynikach i newsach regulacyjnych.',
		keyLevels: ['220', '210', '205', '198', '192'],
		indicators: ['MA(50) jako wsparcie trendowe', 'RSI: dywergencje na szczytach', 'Wolumen przy wybiciach jako filtr jakości ruchu'],
		volatility: 'ATR umiarkowany; podwyższony w okolicach raportów kwartalnych i guidance.',
		scenarioNotes: [
			'Akceptacja nad 210 → retest 220, jeśli sektor mega-cap wspiera ruch.',
			'Zamknięcie pod 205 → ryzyko zejścia w 198/192.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'tsla-d1',
		asset: 'TSLA',
		timeframe: 'D1',
		trend: 'Zmienny trend z częstymi gwałtownymi korektami; wrażliwy na marże, produkcję i konkurencję.',
		keyLevels: ['280', '260', '240', '225', '210'],
		indicators: ['MA(50) często złamane w korektach', 'RSI skłonny do przegrzań', 'Wolumen wybicia krytyczny dla jakości ruchu'],
		volatility: 'ATR wysoki; skoki przy raportach, zmianach cen i wiadomościach branżowych.',
		scenarioNotes: [
			'Powrót nad 260 z wolumenem → cel 280.',
			'Zamknięcie pod 240 → otwiera drogę do 225/210.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'nvda-d1',
		asset: 'NVDA',
		timeframe: 'D1',
		trend: 'Silny trend wzrostowy napędzany popytem na GPU/AI; wrażliwy na guidance i podaż.',
		keyLevels: ['140', '132', '125', '118', '110'],
		indicators: ['MA(50) trzyma trend', 'RSI często przegrzany podczas parabolicznych fal', 'Wolumen i szerokość ruchu w półprzewodnikach'],
		volatility: 'ATR wysoki; szczególnie podczas raportów i konferencji branżowych.',
		scenarioNotes: [
			'Obrona 132 → ponowny test 140 przy silnym SOX.',
			'Złamanie 125 → ryzyko zejścia do 118/110.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'msft-d1',
		asset: 'MSFT',
		timeframe: 'D1',
		trend: 'Trend wzrostowy wspierany chmurą i AI; korekty zwykle płytkie.',
		keyLevels: ['470', '455', '445', '430'],
		indicators: ['MA(50) jako wsparcie', 'RSI z umiarkowanymi przegrzaniami', 'Korelacja z NASDAQ 100'],
		volatility: 'ATR umiarkowany; podwyższony przy raportach i newsach AI.',
		scenarioNotes: [
			'Akceptacja nad 455 → szansa na 470.',
			'Domknięcie pod 445 → test 430.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'amzn-d1',
		asset: 'AMZN',
		timeframe: 'D1',
		trend: 'Wzrostowy kanał wspierany marżami e-commerce i chmurą; ryzykiem są spowolnienia konsumpcji.',
		keyLevels: ['200', '192', '186', '178'],
		indicators: ['MA(50) i MA(200) — układ byczy', 'RSI: przegrzania krótkotrwałe', 'Wolumen przy wybiciach'],
		volatility: 'ATR umiarkowany; silniejszy przy raportach i guidance.',
		scenarioNotes: [
			'Obrona 192 → powrót do 200.',
			'Zamknięcie pod 186 → kierunek 178.',
		],
		updatedAt: new Date().toISOString(),
	},
	{
		id: 'meta-d1',
		asset: 'META',
		timeframe: 'D1',
		trend: 'Silny trend wzrostowy; wrażliwy na CAPEX/metaverse i dynamikę ARPU.',
		keyLevels: ['540', '520', '500', '480'],
		indicators: ['MA(50) utrzymuje trend', 'RSI: przegrzania na wybiciach', 'Szerokość ruchu w komunikacji/ads'],
		volatility: 'ATR umiarkowany do wysokiego; skacze przy raportach i zmianach w polityce reklamowej.',
		scenarioNotes: [
			'Akceptacja nad 520 → retest 540.',
			'Złamanie 500 → kierunek 480.',
		],
		updatedAt: new Date().toISOString(),
	},
];

